#!/usr/bin/env python3
"""The build's output, against the output that is committed.

    python3 tests/test_golden.py

WHY THIS EXISTS NOW. The rules engine is written twice — tiebreaker.py and
site/engine.js, clinch/odds/chaos and site/race.js — and the plan is to make
the JavaScript side the only copy and have build.py call it. Every step of
that moves code that decides what the pages say. test_parity.py proves the two
engines agree with each other; nothing proves that the pages did not change.
This does.

THE COMMITTED TREE IS THE GOLDEN, and that is the whole trick. site/,
site_pools/ and site_schedule/ are generated and committed, and a rebuild
reproduces them byte for byte — write_if_unchanged_skip means even the files
carrying a clock are left alone when only the clock moved. So there is no
manifest to store, nothing to re-record by hand, and nothing that can go stale:
the baseline is whatever HEAD says the site looks like.

A stored hash manifest was the other option and it is worse. It has to be
regenerated by a human every time the output legitimately moves, which is
every week the data changes, and a manifest nobody trusts is a test nobody
runs.

WHAT COUNTS AS AN ALLOWED CHANGE. Not a distinction this file can make, and it
deliberately does not try. An earlier draft hardcoded a "numeric" set — the
files that carry Monte Carlo output and are therefore allowed to move when the
PRNG changes — derived by rebuilding with a perturbed seed and diffing. Run in
August that derivation returns seven files and does not include standings.csv,
because preseason the CSV is a header and no rows. In November it is sixteen
rows of unrounded p_ccg and moves with every reseed. A classification that is
wrong in the half of the season that matters is worse than none.

So: any difference fails, and the diff is printed. The reader decides. During
the engine port that reads as —

  * porting the rules (tiebreaker.py -> engine.js): NOTHING may move. Those
    functions have no RNG in them. A difference here is a port bug.
  * porting odds.py: the odds files move exactly once, because mulberry32
    replaces random.gauss and A&S 7.1.26 replaces math.erf. Read the diff,
    convince yourself it is only the numbers, commit the new output with the
    port, and this goes green again on the new baseline.
"""
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
TB = os.path.dirname(HERE)
ROOT = os.path.dirname(TB)
TREES = ("site", "site_pools", "site_schedule")

# The committed pages are built with the pools section on — pages.yml decides
# from the date, and what is in git is the lit assembly. Building dark here
# would differ from the baseline by the whole section and prove nothing.
ENV = dict(os.environ, B12_PICKEM="1")

# The clocks, blanked before comparing — the same three build.py itself
# excludes when it decides whether a file needs rewriting at all
# (build.py:4647, :4678, and assemble.sh's stamp). They are not content: a
# file whose only difference is one of these did not change what it says.
#
# Blanking them matters twice. Once so a clock does not fail the test, and
# once so the first-difference display below points at the real change: when
# an odds file IS rewritten it gets a fresh "generated" too, and unblanked
# that timestamp is what shows up as the first differing byte, several
# thousand characters before the number that actually moved.
CLOCKS = re.compile(
    r'\{\{BUILD_STAMP\}\}'
    r'|updated [A-Z][a-z]+ \d+, \d\d:\d\d UTC'
    r'|<lastBuildDate>[^<]*</lastBuildDate>'
    r'|"generated": "[^"]*"')


def tracked_and_clean():
    """The baseline is only a baseline if it is what HEAD says it is."""
    out = subprocess.run(["git", "-C", ROOT, "status", "--porcelain", "--"]
                         + [os.path.join("tiebreaker", t) for t in TREES],
                         capture_output=True, text=True)
    return [l for l in out.stdout.splitlines() if l.strip()]


def build_into(dst):
    """Build a copy of the tree, so the working copy is untouched either way.

    The copy needs a sibling attendance/ or it silently builds a smaller site:
    facts.py reads ../attendance/data/attendance.csv (facts.py:125), which is
    the only thing the build opens outside tiebreaker/. Without it facts.json
    loses its whole attendance section and hub.json loses its numbers — no
    error, just less. tools/verify-deterministic.sh copies the same way and
    never noticed, because it compares two builds that are both missing it.
    A symlink: nothing writes there.
    """
    shutil.copytree(TB, dst, symlinks=True,
                    ignore=shutil.ignore_patterns("__pycache__", ".env"))
    os.symlink(os.path.join(ROOT, "attendance"),
               os.path.join(os.path.dirname(dst), "attendance"))
    r = subprocess.run([sys.executable, "build.py"], cwd=dst, env=ENV,
                       capture_output=True, text=True)
    if r.returncode:
        sys.exit(f"the build failed, so there is nothing to compare:\n"
                 f"{r.stdout[-2000:]}\n{r.stderr[-2000:]}")


def show(old_path, new_path, label, window=90):
    """The first place two generated files disagree, with context.

    Not `diff -u`: these pages are close to single-line — the whole Brief is
    one <p> and a run of <div>s with no newline in it — so a unified diff is
    kilobytes of a single -/+ pair with the change buried somewhere in the
    middle. What a reader wants is the first byte that differs and the text
    either side of it, which for an odds change is the number and the team's
    name next to it.
    """
    a = CLOCKS.sub("", open(old_path, encoding="utf-8",
                            errors="replace").read())
    b = CLOCKS.sub("", open(new_path, encoding="utf-8",
                            errors="replace").read())
    i = next((k for k in range(min(len(a), len(b))) if a[k] != b[k]),
             min(len(a), len(b)))
    lo = max(0, i - window)
    cut = lambda s: (("..." if lo else "")
                     + s[lo:i + window].replace("\n", "\\n")
                     + ("..." if i + window < len(s) else ""))
    line = a.count("\n", 0, i) + 1
    print(f"  {label}, first difference at line {line}, byte {i}:")
    print(f"    committed: {cut(a)}")
    print(f"    built:     {cut(b)}")
    print()


def walk(root):
    for dirpath, _, names in os.walk(root):
        for n in names:
            p = os.path.join(dirpath, n)
            yield os.path.relpath(p, root), p


def main():
    dirty = tracked_and_clean()
    if dirty:
        print("the generated tree is not what HEAD says it is, so it cannot "
              "be the baseline. Commit or revert first:\n")
        for l in dirty[:20]:
            print(f"  {l}")
        if len(dirty) > 20:
            print(f"  ... and {len(dirty) - 20} more")
        sys.exit(1)

    tmp = tempfile.mkdtemp(prefix="golden-")
    try:
        fresh = os.path.join(tmp, "tb")
        build_into(fresh)

        moved, missing, added, n = [], [], [], 0
        for tree in TREES:
            base, new = os.path.join(TB, tree), os.path.join(fresh, tree)
            have = dict(walk(base)) if os.path.isdir(base) else {}
            got = dict(walk(new)) if os.path.isdir(new) else {}
            for rel in sorted(have):
                if rel not in got:
                    missing.append(f"{tree}/{rel}")
                    continue
                n += 1
                a = open(have[rel], "rb").read()
                b = open(got[rel], "rb").read()
                if a == b:
                    continue
                # Only the deploy stamp moved: not a change in what the page
                # says, and assemble.sh rewrites it anyway.
                ta = CLOCKS.sub("", a.decode("utf-8", "replace"))
                tb_ = CLOCKS.sub("", b.decode("utf-8", "replace"))
                if ta != tb_:
                    moved.append(f"{tree}/{rel}")
            added += [f"{tree}/{rel}" for rel in sorted(got) if rel not in have]

        if not (moved or missing or added):
            print(f"golden: {n} generated files, all byte-identical to HEAD")
            return 0

        print("the build no longer reproduces the committed site.\n")
        for label, items in (("changed", moved), ("no longer built", missing),
                             ("newly built", added)):
            if items:
                print(f"  {label} ({len(items)}):")
                for f in items[:25]:
                    print(f"    {f}")
                if len(items) > 25:
                    print(f"    ... and {len(items) - 25} more")
                print()

        if moved:
            for f in moved[:3]:
                show(os.path.join(TB, f), os.path.join(fresh, f), f)
        print("\nIf this is the odds port, that is the one change it is "
              "allowed to make:\nread the diff, then commit the new output "
              "with it. Otherwise it is a bug.")
        return 1
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
