#!/usr/bin/env python3
"""The deploy schedule, derived from when games actually kick off.

    python3 gen_cron.py            # print the block for the live season
    python3 gen_cron.py 2025       # any season we have kickoffs for
    python3 gen_cron.py --cost     # what it would cost, month by month

WHY THIS EXISTS. pages.yml currently fires on a blanket schedule — hourly all
weekend, every two hours on some weekday mornings, daily otherwise — about 300
times a month whether or not a ball is in the air. Most of those runs fetch a
scores file that has not changed since the last one.

There are only ~33 game days in a season. A run is worth making in the window
where a result might actually land: from 3h30 after the day's first kickoff
(the earliest a game can be final) to 5h after its last (a safe margin past
the last whistle). Outside that window nothing has changed.

Derived, not hand-written, because kickoff times move: 67 of 2026's 120 games
still have no announced time in mid-August, and they arrive about two weeks
out. So this is meant to be re-run weekly and the block re-committed — and a
daily catch-all stays in the schedule regardless, so a game whose time was
never announced is still picked up within a day.

It PRINTS. Nothing here edits a workflow; putting the block in is a separate,
deliberate step, because a script that rewrites its own trigger while running
on that trigger is a thing to do on purpose or not at all.
"""
import collections
import datetime
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")

READY_AFTER_FIRST = datetime.timedelta(hours=3, minutes=30)
SAFE_AFTER_LAST = datetime.timedelta(hours=5)


def kickoffs(year):
    """Confirmed kickoffs only. A TBD carries a placeholder hour, and a
    schedule built on placeholders is a schedule aimed at midnight."""
    path = os.path.join(DATA, f"games_{year}.json")
    if not os.path.exists(path):
        sys.exit(f"no schedule at {path}")
    games = json.load(open(path))
    out, tbd = [], 0
    for g in games:
        if not g.get("start"):
            continue
        if g.get("start_tbd"):
            tbd += 1
            continue
        out.append(datetime.datetime.fromisoformat(
            g["start"].replace("Z", "+00:00")).astimezone(datetime.timezone.utc))
    return out, tbd, len(games)


def windows(times):
    """One (start, end) per day that has games, in UTC."""
    byday = collections.defaultdict(list)
    for t in times:
        byday[t.date()].append(t)
    for d in sorted(byday):
        ks = sorted(byday[d])
        yield ks[0] + READY_AFTER_FIRST, ks[-1] + SAFE_AFTER_LAST, len(ks)


def slots(times):
    """Every UTC hour a run should happen, as (month, day, hour)."""
    seen = set()
    for start, end, _ in windows(times):
        t = start.replace(minute=0, second=0, microsecond=0)
        if t < start:
            t += datetime.timedelta(hours=1)
        while t <= end:
            seen.add((t.month, t.day, t.hour))
            t += datetime.timedelta(hours=1)
    return sorted(seen)


def to_cron(sl):
    """Collapse the slots into as few cron lines as the shape allows.

    One line per (month, day) with its hours listed, which is exact and
    readable. GitHub takes a list of schedules; there is no reward for being
    clever with ranges here, and a line a person can check against a fixture
    list is worth more than a short one."""
    byday = collections.defaultdict(list)
    for m, d, h in sl:
        byday[(m, d)].append(h)
    lines = []
    for (m, d), hrs in sorted(byday.items()):
        hh = ",".join(str(h) for h in sorted(set(hrs)))
        lines.append(f'    - cron: "0 {hh} {d} {m} *"')
    return lines


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("-")]
    year = int(args[0]) if args else 2026
    times, tbd, total = kickoffs(year)
    sl = slots(times)

    if "--cost" in sys.argv:
        per = collections.Counter(m for m, _, _ in sl)
        print(f"{year}: {len(times)} of {total} kickoffs confirmed "
              f"({tbd} TBD)\n")
        print(f"  {'month':<10}{'runs':>6}")
        for m in sorted(per):
            name = datetime.date(year, m, 1).strftime("%B")
            print(f"  {name:<10}{per[m]:>6}")
        print(f"  {'-' * 16}\n  {'season':<10}{len(sl):>6}")
        return

    print(f"# Generated by tiebreaker/gen_cron.py from the {year} kickoffs.")
    print(f"# {len(times)} of {total} confirmed; {tbd} still TBD and covered")
    print(f"# only by the daily catch-all below. Re-run weekly as times are")
    print(f"# announced. {len(sl)} scheduled runs across {len(list(windows(times)))}"
          f" game days.")
    print('    - cron: "0 18 * 8-12 *"        # daily catch-all — TBD games,'
          ' corrections')
    print('    - cron: "0 12 * 8-12 2"        # Tue — the weekly'
          ' ratings/lines refresh')
    for line in to_cron(sl):
        print(line)


if __name__ == "__main__":
    main()
