#!/usr/bin/env python3
"""Generate the cross-language ATS fixture from committed 2025 results.

    python3 worker/test/fixtures/gen_ats_fixture.py

The Worker grades every pick in JavaScript. Nothing else on this site does,
which means the ATS convention has exactly one implementation and no second
opinion — and a reversed sign there is the worst bug this feature can have. It
does not crash. It does not look wrong. It grades an entire season backwards
and the board is plausible the whole way.

So the expected results are derived here, in Python, from a different
arithmetic (the human-readable line as a float, rather than the doubled
integer), and checked in. test/parity.test.js asserts the Worker reproduces
every row; tiebreaker/tests/test_pickem.py asserts this file still matches the
data it was generated from, so it cannot quietly go stale.

2025 is used because it is finished: every game has a result and a closing
line, and neither will ever change again.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tiebreaker"))

import pickem  # noqa: E402

SEASON = 2025


def load(name):
    with open(os.path.join(ROOT, "tiebreaker", "data", name)) as f:
        return json.load(f)


def ats_float(home_points, away_points, spread):
    """Who covered, in the obvious floating-point way.

    Deliberately NOT the Worker's integer form. If the doubling in
    freeze_spread ever stops being equivalent to the arithmetic a person would
    do by hand, that is precisely what this is here to catch.
    """
    adj = (home_points - away_points) + spread
    return "home" if adj > 0 else "away" if adj < 0 else "push"


def build():
    games = load(f"games_{SEASON}.json")
    raw = load(f"lines_{SEASON}.json")
    lines = {k: (v if isinstance(v, dict) else {"spread": v})
             for k, v in raw.items()}

    rows, moved = [], 0
    for g in sorted(games, key=lambda x: x["id"]):
        if not g["completed"] or g["home_points"] is None:
            continue
        spread_raw = (lines.get(str(g["id"])) or {}).get("spread")
        if spread_raw is None:
            continue
        spread_x2 = pickem.freeze_spread(spread_raw)
        frozen = spread_x2 / 2

        # The number the game is actually scored against is the frozen one.
        expected = ats_float(g["home_points"], g["away_points"], frozen)
        # How often rounding a cross-book mean to the half point changes the
        # answer. Reported, not asserted — it is a property of the market.
        if ats_float(g["home_points"], g["away_points"], spread_raw) != expected:
            moved += 1

        rows.append({
            "game_id": g["id"],
            "home": g["home"],
            "away": g["away"],
            "home_points": g["home_points"],
            "away_points": g["away_points"],
            "spread_raw": spread_raw,
            "spread_x2": spread_x2,
            # Independent statement of the sign convention, taken from
            # scorecard.py:tally — the favorite is the home team when the
            # spread is negative. This is the assertion that catches an
            # inverted sign even if the arithmetic happens to agree.
            "favorite": (None if spread_raw == 0 else
                          g["home"] if spread_raw < 0 else g["away"]),
            "ats": expected,
        })

    payload = {
        "season": SEASON,
        "note": ("Generated by gen_ats_fixture.py from committed data. "
                 "Expected values are derived in Python with float "
                 "arithmetic; the Worker must reproduce them with integers."),
        "games": rows,
    }
    return payload, moved


def serialise(payload):
    """The exact bytes of the committed fixture."""
    return json.dumps(payload, indent=1, sort_keys=True) + "\n"


PATH = os.path.join(HERE, f"ats-{SEASON}.json")


def main():
    payload, moved = build()
    rows = payload["games"]
    with open(PATH, "w") as f:
        f.write(serialise(payload))
    out = PATH

    counts = {k: sum(1 for r in rows if r["ats"] == k)
              for k in ("home", "away", "push")}
    print(f"{len(rows)} graded games -> {out}")
    print(f"  home covers {counts['home']}, away {counts['away']}, "
          f"push {counts['push']}")
    print(f"  half-point freeze changed the result in {moved} of {len(rows)}")


if __name__ == "__main__":
    main()
