// Does the Worker grade a real season the way Python says it should?
//
// In the spirit of tiebreaker/tests/test_parity.py, which keeps engine.js and
// tiebreaker.py from drifting. The risk here is narrower and nastier: the ATS
// convention exists in exactly one place in production, and getting its sign
// backwards produces a season of confidently wrong results with no symptom.
//
// The fixture is generated by fixtures/gen-ats-fixture.py from committed 2025
// data, using float arithmetic on the human-readable line. This file asserts
// the Worker reaches the same answer with integer arithmetic on the doubled
// one. Two languages, two representations, one expected result.

import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { ats, outcome, displaySpread } from "../src/ats.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIX = JSON.parse(
  readFileSync(join(HERE, "fixtures", "ats-2025.json"), "utf8"));

test("the fixture is a real season, not a stub", () => {
  assert.equal(FIX.season, 2025);
  assert.ok(FIX.games.length >= 100,
    `only ${FIX.games.length} graded games — the fixture looks truncated`);
  // If every game came out the same way, the fixture proves nothing.
  const kinds = new Set(FIX.games.map((g) => g.ats));
  assert.deepEqual([...kinds].sort(), ["away", "home", "push"]);
});

test("every graded game agrees, Python float vs Worker integer", () => {
  const wrong = [];
  for (const g of FIX.games) {
    const got = ats(g.home_points, g.away_points, g.spread_x2);
    if (got !== g.ats) {
      wrong.push(`${g.away} at ${g.home} ${g.away_points}-${g.home_points} ` +
                 `line ${g.spread_x2 / 2}: python ${g.ats}, worker ${got}`);
    }
  }
  assert.deepEqual(wrong, [],
    `${wrong.length} of ${FIX.games.length} games graded differently`);
});

test("the sign convention matches scorecard.py's, independently", () => {
  // The arithmetic above could agree while the whole convention is inverted —
  // both sides would simply be wrong together. `favourite` in the fixture
  // comes from scorecard.py's rule (home is favoured when the spread is
  // negative), which was written years before any of this and is used to
  // score the market on the tiebreaker's model card.
  //
  // Derive the favourite from the Worker instead: give that side an
  // implausible blowout and see who covers.
  const wrong = [];
  for (const g of FIX.games) {
    if (g.favourite === null) continue;          // a pick'em has no favourite
    const homeIsFav = ats(200, 0, g.spread_x2) === "home"
                   && ats(0, 200, g.spread_x2) === "away";
    assert.ok(homeIsFav, "a 200-point win must cover any line");
    // Whoever is laying points sees a negative number.
    const fav = displaySpread(g.spread_x2, "home") < 0 ? g.home : g.away;
    if (fav !== g.favourite) {
      wrong.push(`${g.away} at ${g.home} line ${g.spread_x2 / 2}: ` +
                 `scorecard.py says ${g.favourite}, worker says ${fav}`);
    }
  }
  assert.deepEqual(wrong, []);
});

test("the favourite loses often enough that the test could fail", () => {
  // A guard on the guard. If favourites covered every game, the assertions
  // above would pass on a broken implementation.
  const covers = FIX.games.filter(
    (g) => g.favourite !== null && g.ats !== "push" &&
      g.favourite === (g.ats === "home" ? g.home : g.away)).length;
  const decided = FIX.games.filter(
    (g) => g.favourite !== null && g.ats !== "push").length;
  assert.ok(covers > decided * 0.3 && covers < decided * 0.7,
    `favourites covered ${covers}/${decided} — too lopsided to be a real ` +
    `test of the convention`);
});

test("pushes are graded as pushes for both sides", () => {
  const pushes = FIX.games.filter((g) => g.ats === "push");
  assert.ok(pushes.length > 0, "no pushes in the fixture");
  for (const g of pushes) {
    assert.equal(outcome("home", g.ats), "push");
    assert.equal(outcome("away", g.ats), "push");
    // A push is exactly the margin landing on the number.
    assert.equal(2 * (g.home_points - g.away_points) + g.spread_x2, 0);
  }
});

test("freezing to the half point is what keeps the push alive", () => {
  // The design decision, asserted rather than assumed.
  //
  // CFBD's spread is a mean across books rounded to a tenth. A mean sitting on
  // an arbitrary tenth almost never equals a real margin, so scored raw the
  // push nearly disappears: one in 120 on this season. Rounding to the nearest
  // half pulls the near-whole means onto whole numbers — which are the only
  // lines that can push — and it comes back to five.
  //
  // Note the mechanism is the opposite of what "half point" suggests: a
  // half-point line never pushes. The gain is in what rounding produces, not
  // in the halves themselves.
  const rawPushes = FIX.games.filter(
    (g) => (g.home_points - g.away_points) + g.spread_raw === 0).length;
  const pushes = FIX.games.filter((g) => g.ats === "push").length;

  assert.ok(pushes > rawPushes,
    `frozen pushes ${pushes} vs raw ${rawPushes} — freezing should not ` +
    `reduce them`);
  assert.ok(pushes / FIX.games.length > 0.02,
    `only ${pushes} pushes in ${FIX.games.length} games (` +
    `${(100 * pushes / FIX.games.length).toFixed(1)}%) — a pick'em should ` +
    `push a few percent of the time`);
  // Every frozen push sits on a whole number, which is the mechanism itself.
  for (const g of FIX.games.filter((x) => x.ats === "push")) {
    // `===`, not assert.equal: -14 % 2 is -0 in JavaScript, and
    // assert.equal compares with Object.is, where -0 is not 0.
    assert.ok(g.spread_x2 % 2 === 0,
      `${g.away} at ${g.home}: a push against a half-point line ` +
      `(${g.spread_x2 / 2}) is arithmetically impossible`);
  }
});
